'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.235
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SpyCdr.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _03_HiTech_World_Dialup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("03-HiTech World Dialup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _113() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("113", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _32_find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("32-find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3D_Folders_Open_Folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3D Folders Open Folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _EXIT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EXIT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Aussichten() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aussichten", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_showDVD_L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_showDVD_L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_viewDvd_active() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_viewDvd_active", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Clear_Windows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clear Windows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dr_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dr.", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Epson_Photo_700() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Epson_Photo_700", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eraser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eraser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ExportarExcel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExportarExcel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FauxS_XP__Oynx__V2_Icon_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FauxS-XP (Oynx) V2 Icon 03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FauxS_XP__Oynx__V2_Icon_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FauxS-XP (Oynx) V2 Icon 04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FauxS_XP__Oynx__V2_Icon_07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FauxS-XP (Oynx) V2 Icon 07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FauxS_XP__Oynx__V2_Icon_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FauxS-XP (Oynx) V2 Icon 11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FauxS_XP__Oynx__V2_Icon_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FauxS-XP (Oynx) V2 Icon 14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FauxS_XP__Oynx__V2_Icon_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FauxS-XP (Oynx) V2 Icon 15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FauxS_XP__Oynx__V2_Icon_151() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FauxS-XP (Oynx) V2 Icon 151", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FauxS_XP__Oynx__V2_Icon_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FauxS-XP (Oynx) V2 Icon 19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FauxS_XP__Oynx__V2_Icon_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FauxS-XP (Oynx) V2 Icon 21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FauxS_XP__Oynx__V2_Icon_38() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FauxS-XP (Oynx) V2 Icon 38", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FauxS_XP__Oynx__V2_Icon_41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FauxS-XP (Oynx) V2 Icon 41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FauxS_XP__Oynx__V2_Icon_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FauxS-XP (Oynx) V2 Icon 48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FauxS_XP__Oynx__V2_Icon_67() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FauxS-XP (Oynx) V2 Icon 67", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FauxS_XP__Oynx__V2_Icon_68() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FauxS-XP (Oynx) V2 Icon 68", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FauxS_XP__Universal__V2_Icon_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FauxS-XP (Universal) V2 Icon 10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FauxS_XP__Universal__V2_Icon_23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FauxS-XP (Universal) V2 Icon 23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Floppy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Floppy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_doc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_doc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hi0058_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hi0058_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ho0027_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ho0027-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icon_228() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon 228", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icon_257() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon 257", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icon_264() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon 264", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icon_291() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon 291", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Icon_299() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon 299", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_magnifyingGlass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_magnifyingGlass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property monitor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monitor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mouse_Tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mouse Tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property oi0013_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oi0013-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Question() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Question", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Question2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Question2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Question3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Question3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
